// Generated by FlutterFire CLI.
// Run: flutterfire configure --project=finance-app-4f54c
// See: https://firebase.flutter.dev/docs/cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBnA1YfsdAo7LR7dG3PE86GIPcOX40Ej4',
    appId: '1:314412565105:web:e998440fcb7cc59cf851d0',
    messagingSenderId: '314412565105',
    projectId: 'finance-app-4f54c',
    authDomain: 'finance-app-4f54c.firebaseapp.com',
    storageBucket: 'finance-app-4f54c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDegOR-8Q3DjQercHvykHqUwEjZxIEE8Y8',
    appId: '1:314412565105:android:00b777f42affb6d7f851d0',
    messagingSenderId: '314412565105',
    projectId: 'finance-app-4f54c',
    storageBucket: 'finance-app-4f54c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIznH7hc_5m0Ml7Ots4ZkmGcAL3a38NSM',
    appId: '1:314412565105:ios:2fbe9af4ca94b4d2f851d0',
    messagingSenderId: '314412565105',
    projectId: 'finance-app-4f54c',
    storageBucket: 'finance-app-4f54c.firebasestorage.app',
    iosClientId: '845670274575-bie8pnj6adnrer0kg6k7dsodudj1j921.apps.googleusercontent.com',
    iosBundleId: 'br.com.useinet.financeApp',
  );
}
